from datetime import datetime

RANDOM_SEED = 42

# Legit wallets & transactions  
N_LEGIT_WALLETS = 4000
N_LEGIT_TRANSACTIONS = 25000

# Timing  
START_DATE = datetime(2025, 6, 1)
TIME_RANGE_DAYS = 90

# Ransomware  
N_RANSOMWARE_CAMPAIGNS = 6
RANSOMWARE_VICTIMS_RANGE = (15, 60)
RANSOM_DEMAND_AMOUNTS = [0.1, 0.25, 0.5, 1.0, 2.0, 5.0]
RANSOMWARE_CAMPAIGN_DAYS_RANGE = (14, 60)

# Peeling chains 
N_PEELING_CHAINS = 12
PEELING_CHAIN_LENGTH_RANGE = (5, 20)
PEELING_STARTING_LUMP_SUM_RANGE = (2, 40)

# Mixing  
N_MIXING_CLUSTERS = 5
MIXING_INPUTS_PER_ROUND_RANGE = (8, 25)
MIXING_ROUNDS_PER_CLUSTER_RANGE = (2, 6)
MIXING_DENOMINATIONS = [0.1, 0.5, 1.0, 5.0]

# Network layer
PEERS_PER_TRANSACTION_RANGE = (2, 6)
RELAY_DELAY_RANGE = (0.1, 4.0)
